In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas_datareader.data as pdf

## 包絡線は二つの効率的ポートフォリオから算出できる
効率的ポートフォリオXとYに比率αで投資したときの期待値と分散の組み合わせが包絡線

### 1.資産の期待収益と分散共分散行列から効率的ポートフォリオを求める
資産は４つと仮定

In [7]:
# 分散共分散行列S
S = np.array([[0.1,0.01,0.03,0.05],[0.01,0.3,0.06,-0.04],[0.03,0.06,0.4,0.02],[0.05,-0.04,0.02,0.5]])
#　期待収益率
E = np.array([0.06, 0.08, 0.1, 0.15])
#定数c
c = 0.04

In [10]:
#一つ目の効率的ポートフォリオ
#c=0として計算
Z = np.dot(S.T, E)
X = Z / np.sum(Z)

In [11]:
#二つ目の効率的ポートフォリオ
Z = np.dot(S.T, (E-c))
Y = Z/np.sum(Z)

In [13]:
#各ポートフォリオの統計量
E_X = np.dot(E.T,X)
E_Y = np.dot(E.T,Y)
var_X = np.dot((E-E_X)**2, X)
var_Y = np.dot((E-E_Y)**2, Y)
sigma_X = np.sqrt(var_X)
sigma_Y = np.sqrt(var_Y)
cov_XY = np.dot(np.dot(X.T, E),Y)
corr_XY = cov_XY / (sigma_X*sigma_Y)

In [26]:
cov_XY

array([0.01060509, 0.01246371, 0.0319246 , 0.06078794])

In [25]:
#XとYを比率αで組み合わせる
alphas = np.arange(-1.5, 3, 0.1)
envelop_dev = np.zeros(45)
envelop_ex = np.zeros(45)
for i in range(45):
    alpha = alphas[i]
    envelop_ex[i] = E_X*alpha + E_Y*(1-alpha)
    envelop_dev = np.sqrt((var_X**2)*(alpha**2) + (var_Y**2)*((1-alpha)**2) + 2*alpha*(1-alpha)*cov_XY)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in sqrt
  


In [19]:
alpha.shape

(45,)

In [27]:
(E-E_X)**2

array([0.00311156, 0.0012803 , 0.00024905, 0.00117092])

In [28]:
E-E_X

array([-0.05578134, -0.03578134, -0.01578134,  0.03421866])